name: Build Chromium macOS x64 (Debug)

  on:
    workflow_dispatch:
      inputs:
        version:
          description: 'Chromium version to build'
          required: true
          default: '136.0.7103.113'
          type: string

  jobs:
    build-macos-x64:
      runs-on: macos-13  # Uses Intel x64 runner instead of Apple Silicon
      timeout-minutes: 360  # 6 hours max

      steps:
      - name: Debug - Show environment
        run: |
          echo "=== System Information ==="
          uname -a
          sw_vers
          echo "=== Available tools ==="
          which python3 || echo "python3 not found"
          python3 --version || echo "python3 version failed"
          which ninja || echo "ninja not found"
          ninja --version || echo "ninja version failed"
          which brew || echo "brew not found"
          echo "=== Current directory ==="
          pwd
          ls -la
          echo "=== GitHub runner info ==="
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "RUNNER_OS: $RUNNER_OS"
          echo "RUNNER_ARCH: $RUNNER_ARCH"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug - After checkout
        run: |
          echo "=== After checkout ==="
          pwd
          ls -la
          echo "=== Check if required files exist ==="
          ls -la utils/ || echo "utils directory not found"
          ls -la downloads.ini || echo "downloads.ini not found"
          ls -la pruning.list || echo "pruning.list not found"
          ls -la patches/ || echo "patches directory not found"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Test basic commands
        run: |
          echo "=== Testing basic commands ==="
          python3 --version
          python3 -c "print('Python works')"
          echo "=== Testing brew ==="
          brew --version
          echo "=== Testing ninja install ==="
          if ! command -v ninja &> /dev/null; then
            echo "Installing ninja..."
            brew install ninja
          else
            echo "ninja is already installed"
          fi
          ninja --version
